# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a14aeb91ffd351a94cd6e95d20b415e37298dc0443637e6a598a881611cb6358659d9d3041482ae1b2ddcb46869e68ed4eb1715ae9446bb8174896bd36955322

test:
  secret_key_base: 8212bc39b2b35f91a20252de58587aeb5029558e50b41a7dfe9d9d433eba7a5ea19234dd5c93edbed21273d478ff90d09a4cd6c64472fd77482a25f60b1afece

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
